### ISSUE TITLE
Error:Kotlin: Unsupported plugin option: org.jetbrains.kotlin.android:enabled=true

### ISSUE THREAD

**Issue by tea9** [ollide/intellij-java2smali#16]
Error:Kotlin: Unsupported plugin option: org.jetbrains.kotlin.android:enabled=true

android studio 3.3 version use build Compile to smali  complains.
kotlin_version = '1.2.71'
gradle:3.2.1
![image](https://user-images.githubusercontent.com/39117901/51507467-0dc63a80-1e2c-11e9-9f02-840b04fb71d6.png)

**Comment by tea9** [comment]
java product is
Error:(11, 25) java: package R does not exist

**Comment by undefo** [comment]
+1
java: package R does not exist
Android Studio 3.3.1

**Comment by nirmalrevar** [comment]
Same issue Android studio 3.4

**Comment by aixiaozi** [comment]
Same issue Android studio 3.4

**Comment by androidovshchik** [comment]
The same issue
I have also updated kotlin version upto 1.3.41 in plugin
But it doesn't work
I have no idea
As workaround you can convert Kotlin to Java which is working with plugin
Via menu `Tools/Kotlin/ Show Kotlin bytecode`
Then click button Decompile and get java code
Edit a little it and you will get working code

**Comment by ollide** [comment]
I've just released a new version of the plugin (2.0.1) which delegates the build job better than before and therefore should fix these kind of errors. Can anyone who encountered this problem post an update whether this still is an issue?
