### ISSUE TITLE
Error:Abnormal build process termination

### ISSUE THREAD

**Issue by wzgiceman** [ollide/intellij-java2smali#17]
Error:Abnormal build process termination: 
"/Applications/Android Studio 2.app/Contents/jre/jdk/Contents/Home/bin/java" -Xmx4096 -Djava.awt.headless=true -Djava.endorsed.dirs=\"\" -Djdt.compiler.useSingleThread=true -Dpreload.project.path=/Users/apple/Documents/git_work/calwin -Dpreload.config.path=/Users/apple/Library/Preferences/AndroidStudio3.3/options -Dcompile.parallel=true -Drebuild.on.dependency.change=true -Djava.net.preferIPv4Stack=true -Dio.netty.initialSeedUniquifier=-6398992184108619455 -XX:MaxPerMSize=2048 -Dfile.encoding=UTF-8 -Duser.language=zh -Duser.country=CN -Didea.paths.selector=AndroidStudio3.3 "-Didea.home.path=/Applications/Android Studio 2.app/Contents" -Didea.config.path=/Users/apple/Library/Preferences/AndroidStudio3.3 "-Didea.plugins.path=/Users/apple/Library/Application Support/AndroidStudio3.3" -Djps.log.dir=/Users/apple/Library/Logs/AndroidStudio3.3/build-log "-Djps.fallback.jdk.home=/Applications/Android Studio 2.app/Contents/jre/jdk/Contents/Home" -Djps.fallback.jdk.version=1.8.0_152-release -Dio.netty.noUnsafe=true -Djava.io.tmpdir=/Users/apple/Library/Caches/AndroidStudio3.3/compile-server/calwin_3224c5d3/_temp_ -Djps.backward.ref.index.builder=true -Dkotlin.incremental.compilation=true -Dkotlin.incremental.compilation.js=true -Dkotlin.daemon.enabled -Dkotlin.daemon.client.alive.path=\"/var/folders/z6/_rpnq0z10wnd68nsllyy2xfc0000gn/T/kotlin-idea-4547390362373460551-is-running\" -classpath "/Applications/Android Studio 2.app/Contents/lib/jps-launcher.jar:/Applications/Android Studio 2.app/Contents/jre/jdk/Contents/Home/lib/tools.jar:/Applications/Android Studio 2.app/Contents/lib/optimizedFileManager.jar" org.jetbrains.jps.cmdline.Launcher "/Applications/Android Studio 2.app/Contents/lib/resources_en.jar:/Applications/Android Studio 2.app/Contents/lib/jna.jar:/Applications/Android Studio 2.app/Contents/lib/forms_rt.jar:/Applications/Android Studio 2.app/Contents/lib/forms-1.1-preview.jar:/Applications/Android Studio 2.app/Contents/lib/aether-transport-file-1.1.0.jar:/Applications/Android Studio 2.app/Contents/lib/commons-logging-1.2.jar:/Applications/Android Studio 2.app/Contents/lib/oro-2.0.8.jar:/Applications/Android Studio 2.app/Contents/lib/jdom.jar:/Applications/Android Studio 2.app/Contents/lib/plexus-component-annotations-1.6.jar:/Applications/Android Studio 2.app/Contents/lib/jps-model.jar:/Applications/Android Studio 2.app/Contents/lib/protobuf-java-3.4.0.jar:/Applications/Android Studio 2.app/Contents/lib/aether-util-1.1.0.jar:/Applications/Android Studio 2.app/Contents/lib/httpcore-4.4.9.jar:/Applications/Android Studio 2.app/Contents/lib/aether-spi-1.1.0.jar:/Applications/Android Studio 2.app/Contents/lib/netty-codec-4.1.25.Final.jar:/Applications/Android Studio 2.app/Contents/lib/netty-buffer-4.1.25.Final.jar:/Applications/Android Studio 2.app/Contents/lib/plexus-utils-3.0.22.jar:/Applications/Android Studio 2.app/Contents/lib/jna-platform.jar:/Applications/Android Studio 2.app/Contents/lib/platform-api.jar:/Applications/Android Studio 2.app/Contents/lib/commons-codec-1.10.jar:/Applications/Android Studio 2.app/Contents/lib/idea_rt.jar:/Applications/Android Studio 2.app/Contents/lib/trove4j.jar:/Applications/Android Studio 2.app/Contents/lib/jps-builders-6.jar:/Applications/Android Studio 2.app/Contents/lib/maven-aether-provider-3.3.9.jar:/Applications/Android Studio 2.app/Contents/lib/lz4-1.3.0.jar:/Applications/Android Studio 2.app/Contents/lib/aether-connector-basic-1.1.0.jar:/Applications/Android Studio 2.app/Contents/lib/maven-model-builder-3.3.9.jar:/Applications/Android Studio 2.app/Contents/lib/log4j.jar:/Applications/Android Studio 2.app/Contents/lib/aether-dependency-resolver.jar:/Applications/Android Studio 2.app/Contents/lib/jps-builders.jar:/Applications/Android Studio 2.app/Contents/lib/netty-common-4.1.25.Final.jar:/Applications/Android Studio 2.app/Contents/lib/asm-all.jar:/Applications/Android Studio 2.app/Contents/lib/nanoxml-2.2.3.jar:/Applications/Android Studio 2.app/Contents/lib/util.jar:/Applications/Android Studio 2.app/Contents/lib/javac2.jar:/Applications/Android Studio 2.app/Contents/lib/aether-api-1.1.0.jar:/Applications/Android Studio 2.app/Contents/lib/maven-repository-metadata-3.3.9.jar:/Applications/Android Studio 2.app/Contents/lib/annotations-java5.jar:/Applications/Android Studio 2.app/Contents/lib/aether-transport-http-1.1.0.jar:/Applications/Android Studio 2.app/Contents/lib/maven-artifact-3.3.9.jar:/Applications/Android Studio 2.app/Contents/lib/maven-model-3.3.9.jar:/Applications/Android Studio 2.app/Contents/lib/commons-lang3-3.4.jar:/Applications/Android Studio 2.app/Contents/lib/aether-impl-1.1.0.jar:/Applications/Android Studio 2.app/Contents/lib/netty-transport-4.1.25.Final.jar:/Applications/Android Studio 2.app/Contents/lib/httpclient-4.5.5.jar:/Applications/Android Studio 2.app/Contents/lib/guava-23.6-jre.jar:/Applications/Android Studio 2.app/Contents/lib/maven-builder-support-3.3.9.jar:/Applications/Android Studio 2.app/Contents/lib/plexus-interpolation-1.21.jar:/Applications/Android Studio 2.app/Contents/lib/netty-resolver-4.1.25.Final.jar:/Applications/Android Studio 2.app/Contents/lib/slf4j-api-1.7.25.jar:/Applications/Android Studio 2.app/Contents/plugins/gradle/lib/gradle-api-4.8.jar:/Applications/Android Studio 2.app/Contents/plugins/gradle/lib/gradle-api-impldep-4.8.jar:/Applications/Android Studio 2.app/Contents/lib/ant/lib/ant.jar:/Applications/Android Studio 2.app/Contents/lib/groovy-all-2.4.15.jar:/Applications/Android Studio 2.app/Contents/lib/gson-2.8.4.jar:/Applications/Android Studio 2.app/Contents/lib/slf4j-api-1.7.25.jar:/Applications/Android Studio 2.app/Contents/lib/slf4j-log4j12-1.7.25.jar:/Applications/Android Studio 2.app/Contents/lib/gson-2.8.4.jar:/Applications/Android Studio 2.app/Contents/plugins/android/lib/jarutils.jar:/Applications/Android Studio 2.app/Contents/lib/guava-23.6-jre.jar:/Applications/Android Studio 2.app/Contents/lib/android-base-common.jar:/Applications/Android Studio 2.app/Contents/plugins/gradle/lib/gradle-api-4.8.jar:/Applications/Android Studio 2.app/Contents/lib/gson-2.8.4.jar:/Applications/Android Studio 2.app/Contents/plugins/android/lib/jarutils.jar:/Applications/Android Studio 2.app/Contents/lib/guava-23.6-jre.jar:/Applications/Android Studio 2.app/Contents/lib/android-base-common.jar:/Applications/Android Studio 2.app/Contents/plugins/gradle/lib/gradle-api-4.8.jar:/Applications/Android Studio 2.app/Contents/plugins/IntelliLang/lib/intellilang-jps-plugin.jar:/Applications/Android Studio 2.app/Contents/plugins/Groovy/lib/groovy-jps-plugin.jar:/Applications/Android Studio 2.app/Contents/plugins/Groovy/lib/groovy-rt-constants.jar:/Applications/Android Studio 2.app/Contents/plugins/gradle/lib/gradle-jps-plugin.jar:/Applications/Android Studio 2.app/Contents/plugins/Kotlin/lib/jps/kotlin-jps-plugin.jar:/Applications/Android Studio 2.app/Contents/plugins/Kotlin/lib/kotlin-stdlib.jar:/Applications/Android Studio 2.app/Contents/plugins/Kotlin/lib/kotlin-reflect.jar:/Applications/Android Studio 2.app/Contents/plugins/Kotlin/lib/kotlin-plugin.jar:/Applications/Android Studio 2.app/Contents/plugins/android/lib/jps/android-jps-plugin.jar:/Applications/Android Studio 2.app/Contents/plugins/android/lib/android-common.jar:/Applications/Android Studio 2.app/Contents/plugins/android/lib/build-common.jar:/Applications/Android Studio 2.app/Contents/plugins/android/lib/android-rt.jar:/Applications/Android Studio 2.app/Contents/plugins/android/lib/android-extensions-ide.jar:/Applications/Android Studio 2.app/Contents/plugins/android/lib/sdk-common.jar:/Applications/Android Studio 2.app/Contents/plugins/android/lib/repository.jar:/Applications/Android Studio 2.app/Contents/plugins/android/lib/sdklib.jar:/Applications/Android Studio 2.app/Contents/plugins/android/lib/jarutils.jar:/Applications/Android Studio 2.app/Contents/plugins/android/lib/layoutlib-api.jar:/Applications/Android Studio 2.app/Contents/plugins/android/lib/manifest-merger.jar" org.jetbrains.jps.cmdline.BuildMain 127.0.0.1 62989 a5162d63-c196-462b-b68e-6b7c7045fc00 /Users/apple/Library/Caches/AndroidStudio3.3/compile-server
Unrecognized VM option 'MaxPerMSize=2048'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by ollide** [comment]
Hi @wzgiceman,
I've just released a new version of the plugin (2.0.1) which delegates the build job better than before and therefore should fix these kind of errors. Can you post an update whether this still is an issue with the new version?
