### ISSUE TITLE
Error:(24, 25) java: 程序包R不存在   (Android Studio Version3.4.2 )

### ISSUE THREAD

**Issue by lydlovezjr** [ollide/intellij-java2smali#18]
<img width="960" alt="微信截图_20190711232246" src="https://user-images.githubusercontent.com/19246347/61063605-cf045b00-a432-11e9-848e-901be374ea90.png">

**Comment by cloudyfly** [comment]
the same to me

**Comment by lydlovexyz** [comment]
> the same to me
难受啊

**Comment by GeniusPudding** [comment]
same question

**Comment by 13383754499** [comment]
Android Studio Version3.5.1  the same to me

**Comment by 13383754499** [comment]
the same to me（Android Studio version3.5.1）

**Comment by 13383754499** [comment]
see image
![2](https://user-images.githubusercontent.com/32156251/68560105-85785b00-047a-11ea-8b99-4df242d27851.png)
![3](https://user-images.githubusercontent.com/32156251/68560106-8610f180-047a-11ea-9cfb-6d61cbaf8454.png)

**Comment by YijingwanWang** [comment]
The same to me (Android studio 3.4.1)

If you can, comment out the references of the layout file, which can be converted to a file with SmalI syntax, just like those in the diagram. It's not the best way, but it's also useful.

![image](https://user-images.githubusercontent.com/14922509/69117626-432ec980-0acb-11ea-9413-49a9ea157945.png)
![image](https://user-images.githubusercontent.com/14922509/69117704-9d2f8f00-0acb-11ea-96cc-725a98dddbe4.png)

**Comment by lamster2018** [comment]
same question

**Comment by safest-place** [comment]
same question in AS 3.5.3

**Comment by kyriej** [comment]
same 3.5.1

**Comment by youngerier** [comment]
same idea 2019
I comment `CompilerCallback#finished`  
`//    if (errors > 0) return` 
pass the compile

**Comment by ollide** [comment]
I've just released a new version of the plugin (2.0.1) which delegates the build job better than before and therefore should fix these kind of errors. Can anyone who encountered this problem post an update whether this still is an issue?
