### ISSUE TITLE
android  studio 4.0 can not find "Compile to smali"  item

### ISSUE THREAD

**Issue by biaolv** [ollide/intellij-java2smali#22]
I have installed java2smali  correctly,but I can not find the item of “Compile to smali” at  Build item。

![download](https://user-images.githubusercontent.com/8874121/88140792-fa647d00-cc24-11ea-8308-232769a2e61b.png)

![download](https://user-images.githubusercontent.com/8874121/88140926-37307400-cc25-11ea-9b31-0fd4de91c66f.png)

**Comment by ollide** [comment]
Thanks for your report @biaolv 
The `Compile to smali action` is displayed on the `Build` tab, not the `Run` tab. Can you see the entry on this tab?

**Comment by biaolv** [comment]
![image](https://user-images.githubusercontent.com/8874121/88243184-2124c100-ccc2-11ea-8465-ba5c38615ec0.png)

**Comment by biaolv** [comment]
When I install the smalidea plug-in, I can't use it, which conflicts with the new default plug-in SmalI
![1595465916(1)](https://user-images.githubusercontent.com/8874121/88243607-7f05d880-ccc3-11ea-8095-3206d0acca50.jpg)
 support in Android Studio 4.0. I delete the registered patterns "*. SmalI" of the default SmalI plug-in, and add the registered patterns "*. SmalI" of smalidea. I hope I can help you


![image](https://user-images.githubusercontent.com/8874121/88243676-c0968380-ccc3-11ea-8ef5-c8f07d0ca91b.png)

![image](https://user-images.githubusercontent.com/8874121/88243686-cb511880-ccc3-11ea-8d1a-13860c80949a.png)

**Comment by Beelucky** [comment]
> I have installed java2smali correctly,but I can not find the item of “Compile to smali” at Build item。
> 
> ![download](https://user-images.githubusercontent.com/8874121/88140792-fa647d00-cc24-11ea-8308-232769a2e61b.png)
> 
> ![download](https://user-images.githubusercontent.com/8874121/88140926-37307400-cc25-11ea-9b31-0fd4de91c66f.png)

I have a problem with cordova gradle version missing framework !

**Comment by ollide** [comment]
@Beelucky Please take a look on the `Build` tab.

**Comment by ollide** [comment]
@biaolv the `Compile to smali` option is the last item on your screenshot here: https://github.com/ollide/intellij-java2smali/issues/22#issuecomment-662769371

It is only active if you have a Java or Kotlin file opened and active in your editor.

The bundled Smali plugin does not interfer with this plugin.
